startdelay: 0
musicdir: ~/RetroPie/roms/music
restart: true
startsong:
mainprocess: emulationstatio
emulator_names:
  - retroarch
  - ags
  - uae4all2
  - uae4arm
  - capricerpi
  - linapple
  - hatari
  - stella
  - atari800
  - xroar
  - vice
  - daphne
  - reicast
  - pifba
  - osmose
  - gpsp
  - jzintv
  - basiliskll
  - mame
  - advmame
  - dgen
  - openmsx
  - mupen64plus
  - gngeo
  - dosbox
  - ppsspp
  - simcoupe
  - scummvm
  - snes9x
  - pisnes
  - frotz
  - fbzx
  - fuse
  - gemrb
  - cgenesis
  - zdoom
  - eduke32
  - lincity
  - love
  - kodi
  - alephone
  - micropolis
  - openbor
  - openttd
  - opentyrian
  - cannonball
  - tyrquake
  - ioquake3
  - residualvm
  - xrick
  - sdlpop
  - uqm
  - stratagus
  - wolf4sdl
  - solarus
